{% set name = "pyjuliacall" %}
{% set pypi_name = "juliacall" %}
{% set version = "0.9.23" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ pypi_name[0] }}/{{ pypi_name }}/juliacall-{{ version }}.tar.gz
  sha256: 536f2e0f4ccfd34920322121b4353079029123eae81b7200ed1787e49d8053d2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=42
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - pyjuliapkg >=0.1.8,<0.2.dev0

test:
  imports:
    - juliacall
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://github.com/JuliaPy/PythonCall.jl
  summary: Julia and Python in seamless harmony
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MilesCranmer
    - mkitti
